apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyages
spec:
  selector:
    matchLabels:
      app: voyages
      version: v1
  replicas: {{ .Values.replicas}}
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/inject: 'true'
        proxy.istio.io/config: |
          tracing:
            zipkin:
              address: zipkin.istio-system:9411
            sampling: 10
            custom_tags:
              http.header.portal:
                header:
                  name: portal
              http.header.device:
                header:
                  name: device
              http.header.user:
                header:
                  name: user
              http.header.travel:
                header:
                  name: travel
      labels:
        app: voyages
        version: v1
    spec:
      containers:
        - name: voyages
          image: quay.io/kiali/demo_travels_portal:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          securityContext:
            privileged: false
          env:
            - name: LISTEN_ADDRESS
              value: ":8000"
            - name: PORTAL_COORDINATES
              value: "48.861310,2.337418"
            - name: PORTAL_COUNTRY
              value: "France"
            - name: PORTAL_NAME
              value: "voyages.fr"
            - name: TRAVELS_AGENCY_SERVICE
              value: "http://travels.travel-agency:8000"
